### ISSUE TITLE
2nd Breakfast To-do's

### ISSUE THREAD

**Issue by mjohnson518** [mjohnson518/second-breakfast#1]
- [ ] Create Register Page

- [ ] Create Logout Page

- [ ] Add Markdown Editor to Forms Textarea (https://github.com/inacho/bootstrap-markdown-editor) 

- [ ] Maybe add Disqus Comment tools?

- [ ] Add Links to *Featured Posts* sidebar

- [ ] Add post category tags

- [ ] Add view statistics to front page card?
